# Generated by Django 6.0.7 on 2026-08-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='code', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('estimated_time', models.CharField(default='15 mins', max_length=30)),
                ('summary', models.TextField(help_text='2-3 simple sentences explaining the problem.')),
                ('analogy', models.TextField(help_text='Real life analogy story.')),
                ('easy_explanation', models.TextField()),
                ('bengali_explanation', models.TextField()),
                ('intuition', models.TextField(help_text='Why this approach works before syntax.')),
                ('hint1_tiny', models.TextField(default='')),
                ('hint2_better', models.TextField(default='')),
                ('hint3_almost', models.TextField(default='')),
                ('code_python', models.TextField(default='')),
                ('code_cpp', models.TextField(default='')),
                ('code_java', models.TextField(default='')),
                ('code_javascript', models.TextField(default='')),
                ('line_by_line', models.JSONField(default=list)),
                ('dry_run_steps', models.JSONField(default=list)),
                ('time_complexity', models.CharField(default='O(n)', max_length=50)),
                ('time_complexity_reason', models.TextField(default='')),
                ('space_complexity', models.CharField(default='O(1)', max_length=50)),
                ('space_complexity_reason', models.TextField(default='')),
                ('common_mistakes', models.JSONField(default=list)),
                ('eli10_explanation', models.TextField(default='', help_text="Explain like I'm 10 version")),
                ('extra_example', models.JSONField(default=dict, help_text='Another example with inputs and walkthrough')),
                ('is_daily_problem', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.topic')),
            ],
            options={
                'ordering': ['id_number'],
            },
        ),
    ]
